# <?php die(); ?>

## 注意：书写时，缩进不能使用 Tab，必须使用空格

#############################
# 数据库设置
#############################

# devel 模式
devel:
  driver:     mysqli
  host:       localhost
  login:      root
  password:   root
  database:   finance
  charset:    utf8
  prefix:

# test 模式
test:
  driver:     mysqli
  host:       localhost
  login:      root
  password:   root
  database:   finance
  charset:    utf8
  prefix:

# deploy 模式
deploy:
  driver:     mysqli
  host:       localhost
  login:      root
  password:   root
  database:   finance
  charset:    utf8
  prefix:

